	AREA SumOfSquares, CODE, READONLY
ENTRY
	LDR R0, =NUMBERS 
	MOV R1, #0 
	MOV R2, #5 
LOOP
	LDR R3, [R0] 
	MUL R4, R3, R3 
	ADD R1, R1, R4 
	ADD R0, R0, #4 
	SUBS R2, R2, #1 
	BNE LOOP 
HERE B HERE 
NUMBERS DCD 1, 2, 3, 4, 5 
	END
